#!/usr/bin/env python3

THE_LIST = {
  '4chan':'',
  'adolfhitler':'',
  'againstrightwingsubs':'Small parody run by racists',
  'altright':'',
  'altrightsub':'',
  'anarcho_capitalism':'',
  'antifa':'Controlled by neo nazis',
  'antipozi':'',
  'antiracism':'Controlled by neo-nazis',
  'apefrica':'',
  'apewrangling':'',
  'argentina':'Controlled by alt-right',
  'asianmasculinity':'',
  'asktrumpsupporters':'',
  'aznidentity':'',
  'beatingcripples':'',
  'beatingniggers':'',
  'beatingtrannies':'',
  'beatingwomen2':'',
  'blackcrime':'',
  'blackfathers':'',
  'blackhusbands':'',
  'blackpeopletwitter':'',
  'burzum':'',
  'canada':'Frequent blatant white supremacy talk',
  'capitalism':'Sexism, Classism, Racism',
  'chairmanpao':'Sexism',
  'chicongo':'',
  'chimpiremeta':'',
  'chimpireofftopic':'',
  'chimpmusic':'',
  'chimpout':'',
  'choosingbeggars':'',
  'commonfilth':'',
  'conservative':'Sexism, Classism, Racism',
  'conspiracy':'',
  'coontown':'',
  'cringe':'',
  'cringeanarchy':'',
  'cringepics':'',
  'dankmemes':'',
  'darkenlightenment':'Alt-right LARPers',
  'debatealtright':'',
  'detoilet':'',
  'dgu':'Not a hate sub, but has quite a few racist people',
  'didntdonuffins':'',
  'drama':'',
  'dylannroofinnocent':'',
  'easternsunrising':'Actual Asian supremacy sub',
  'edefreiheit':'German speaking hate sub',
  'ellenpaohate':'',
  'european':'',
  'europeannationalism':'',
  'facebookcleavage':'',
  'farright':'',
  'fatlogic':'',
  'fatpeoplehate':'',
  'fatpeoplestories':'',
  'funnyniggers':'',
  'gasthekikes':'',
  'gasthesnoo':'',
  'gender_critical':'',
  'gendercritical':'',
  'gentilesunited':'Anti-semitism',
  'gibsmedat':'',
  'gott_mit_uns':'',
  'greatapes':'',
  'greentext':'',
  'hbd':'',
  'hillaryforprison':'',
  'holdmyfries':'',
  'holocaust':'',
  'hottiesfortrump':'',
  'im14andthisisdeep':'',
  'imgoingtohellforthis':'',
  'incel':'',
  'incels':'',
  'infowars':'',
  'internationalnews':'',
  'ipcirclejerk':'zionism',
  'israel':'zionism',
  'israelsubredditwatch':'Anti-Arab',
  'justblackgirlthings':'',
  'justiceserved':'Frequent racism',
  'kangz':'',
  'killingwomen':'',
  'kkk':'',
  'kotakuinaction':'',
  'le_pen':'',
  'liberal':'',
  'liberaldegeneracy':'',
  'libertarian':'',
  'mensrights':'',
  'metacanada':'',
  'mgtow':'',
  'monarchism':'',
  'mongoloidsupremacy':'',
  'moonman_industries':'',
  'muhdick':'',
  'murica':'',
  'n1ggers':'',
  'nationalism':'',
  'nationalsocialism':'',
  'nazi':'',
  'negrofree':'',
  'neoliberal':'',
  'new_right':'',
  'niggercartoons':'',
  'niggerdocumentaries':'',
  'niggerdrama':'',
  'niggerfacts':'',
  'niggerhistorymonth':'',
  'niggermythology':'',
  'niggersgifs':'',
  'niggersnews':'',
  'niggerspics':'',
  'niggersstories':'',
  'niggerstil':'',
  'niggervideos':'',
  'niglets':'',
  'northamerican':'',
  'northwestfront':'',
  'nsbm':'',
  'odalism':'',
  'palestinecirclejerk':'Anti-Arab, zionist',
  'paoyongyang':'I dont even know',
  'pepe':'',
  'physical_removal':'',
  'pissbeuponhim':'',
  'polacks':'',
  'polistan':'',
  'prolife':'Sexism',
  'protectandserve':'Rampant racism and classism',
  'publichealthadvocacy':'',
  'publichealthwatch':'',
  'pussypass':'',
  'pussypassdenied':'',
  'race_realism':'',
  'racerealism':'',
  'racism_immigration':'',
  'racistniggers':'',
  'rapingwomen':'',
  'seduction':'',
  'shadbase':'',
  'shitniggerssay':'',
  'shitpoliticssays':'',
  'shitstatistssay':'',
  'sjsucks':'',
  'sjwhate':'',
  'srssucks':'',
  'stepdownpao':'',
  'strugglefucking':'',
  'subredditcancer':'',
  'talesofprivelege':'',
  'tardfiction':'',
  'tardtales':'',
  'teenapers':'',
  'thathappened':'',
  'the_antijewantiwhite':'',
  'the_donald':'',
  'the_europe':'',
  'the_farage':'',
  'the_italia':'',
  'the_ivanka':'',
  'the_nelen':'',
  'the_nutty':'',
  'the_wilders':'',
  'theracistredpill':'',
  'theredpill':'',
  'therightboycott':'',
  'third_position':'',
  'tnb':'',
  'trans_fags':'',
  'trayvonmartin':'',
  'truecels':'',
  'tumblrinaction':'',
  'uncensorednews':'',
  'uncensorship':'',
  'undelete':'',
  'usblackculture':'',
  'wackytictacs':'',
  'watchniggersdie':'',
  'watchpeopledie':'',
  'weekendgunnit':'',
  'weisssturm':'',
  'wewuzkangs':'',
  'white_nationalism':'',
  'white_pride':'',
  'whitebeauty':'',
  'whiteeurope':'Anti-semitism, Classism, racism, sexism etc',
  'whitenationalism':'',
  'whiterights':'',
  'whitestudentunion':'',
  'whowillbuildtheroads':'',
  'worldstarhp':'',
  'wtfniggers':'',
  'zog':''
}

